name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 10
        
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      id: deploy
      with:
        vercel-token: '5GmB2Jl44nwRPKWLg5YBw90y'
        vercel-project-id: 'prj_LGMVH4OGmCGJRLba176BZ4B7JyVl'
        github-comment: false
        vercel-args: '--prod'
        working-directory: ./
        
    - name: Run E2E Tests
      run: |
        PLAYWRIGHT_TEST_BASE_URL=${{ steps.deploy.outputs.preview-url }} pnpm test:e2e
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30 